version: '3.4'

services:
  frontend:
    image: hello-frontend
    #ports:
    #  - 5001:5001

  backend: 
    image: hello-backend
    #ports:
    #  - 8080:8080
    environment: 
      - REDIS_HOST=redis_host
      - POSTGRES_HOST=postgres-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres

  redis:
    image: redis
    restart: unless-stopped
    container_name: redis_host

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    container_name: postgres-db
  
  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80

volumes:
  database: